POST http://localhost:3001/api/comments/19 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Indyb2JlbEBnbWFpbC5jb20iLCJpZCI6NiwiaWF0IjoxNzEzNzIxMzQ2fQ.QUTZLrcoc8O1KRdbraymwtPHFfyDok9jjIXBw2nZL-Y

{
    "comment": "Drugi komentarz, dodany przez plugin"
}

###

GET http://localhost:3001/api/comments/19 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Indyb2JlbEBnbWFpbC5jb20iLCJpZCI6NiwiaWF0IjoxNzEzNzIxMzQ2fQ.QUTZLrcoc8O1KRdbraymwtPHFfyDok9jjIXBw2nZL-Y

{
}