GET http://localhost:3001/api/teams/members HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbmFnZXJAZ21haWwuY29tIiwiaWQiOjMsImlhdCI6MTcxNzA5MzU0NX0.I0LhNPN-hWhNfqVZkUPVJUv1VdN5QXZWeVfYlnXxWOs

{
}

###

GET http://localhost:3001/api/teams/teamNames HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbmFnZXJAZ21haWwuY29tIiwiaWQiOjMsImlhdCI6MTcxNzA5MzU0NX0.I0LhNPN-hWhNfqVZkUPVJUv1VdN5QXZWeVfYlnXxWOs

{
}