POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MTczNTE3OTR9.nFRmDPHduPtXKNj42wiE2LrvieVAhfk6fK1w7sDMGIA

{
    "name": "Admin",
    "surname": "2.Org",
    "email": "admin_2@gmail.com",
    "password": "password",
    "phone": "+48666666666",
    "admin": true,
    "technologies": [],
    "team": null,
    "project": "",
    "team_lead": false,
    "role": "",
    "is_client": false,
    "organization": 2
}
