POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "name": "test_admin",
    "surname": "test_admin",
    "email": "test_admin@gmail.com",
    "password": "password",
    "phone": "+48111111111"
}