

name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger_frontend_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Trigger Frontend Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.TASKLY_FRONTEND_TOKEN }}" \
          https://api.github.com/repos/Path-Finder-00/taskly-frontend/dispatches \
          -d '{"event_type":"run-workflow"}'

      - name: Wait for Frontend Workflow Completion
        id: wait
        run: |
          repo="Path-Finder-00/taskly-frontend"
          workflow_id="run-workflow"  # replace with your workflow id
          status="in_progress"
          while [[ "$status" == "in_progress" || "$status" == "queued" ]]; do
            sleep 30
            status=$(curl -s -H "Authorization: token ${{ secrets.TASKLY_FRONTEND_TOKEN }}" \
            "https://api.github.com/repos/$repo/actions/runs?event=repository_dispatch" \
            | jq -r '.workflow_runs[] | select(.name=="run-workflow") | .status')
            echo "Current status: $status"
          done
          if [[ "$status" != "completed" ]]; then
            echo "Workflow did not complete successfully"
            exit 1
          fi

  fetch_file:
    needs: trigger_frontend_workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout back-end
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./

      - name: List files
        run: ls -R
      
      - name: Copy dist from front-end
        run: |
          rm -r ./dist/
          cp -r ./dist/ ./dist/

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: fetch_file
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm install
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
